name: Lint and Format Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install isort[requirements_deprecated_finder,pipfile_deprecated_finder]
        pip install pylint
        pip install -r requirements.txt
    - name: Run isort
      run: isort *.py
    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Apply isort formatting'
    - name: Run Pylint
      run: pylint --fail-under=-200 *.py
